### ISSUE TITLE
dimension match problem

### ISSUE THREAD

**Issue by 7color94** [simochen/flowtrack.pytorch#6]
Thanks for your code. However, I meet the following problem, could you help me ?

`Traceback (most recent call last):
  File "preprocess.py", line 40, in <module>
    flow_im = estimate(model, previous, current)
  File "/data00/home/xxxx/flowtrack.pytorch/tools/flownet/demo.py", line 102, in estimate
    pred_flow = model(ims_v).cpu().data
  File "/data00/home/xxxx/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data00/home/xxxx/flowtrack.pytorch/tools/flownet/../../lib/flownet/model/models.py", line 271, in forward
    concat5 = torch.cat((out_conv5,out_deconv5,flow6_up),1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 24 and 23 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:111`

**Comment by simochen** [comment]
Hi, @7color94 . What's your input image size?

**Comment by 7color94** [comment]
Two input images are all (720, 1280, 3).

**Comment by simochen** [comment]
@7color94 This problem is caused by the stride2 convolution and deconvolution after 'out_conv5' layer. You can padding input image and make input size divisible by 64.
