### ISSUE TITLE
run './make.sh' failed

### ISSUE THREAD

**Issue by sklf** [simochen/flowtrack.pytorch#9]
hello, I cloned your project and tried to run it. However, I failed to run './make.sh'. Some error messages are as follow:

`
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/share1/home/chunyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/share1/home/chunyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/share1/home/chunyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/share1/home/chunyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/share1/home/chunyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/share1/home/chunyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling channelnorm kernels by nvcc...
rm: cannot remove 'ChannelNorm_kernel.o': No such file or directory
./make.sh: line 9: nvcc: command not found
gcc: error: /share1/home/chunyang/files/flowtrack.pytorch/lib/flownet/networks/channelnorm_package/src/ChannelNorm_kernel.o: No such file or directory
`
So I want to know what are the  python requirements. Right now my environment are:
Ubuntu16.04
Anaconda3
python 3.6
CUDA 9.0
CUDNN 7.1.2
pytorch 0.4.1

**Comment by simochen** [comment]
Hi, @sklf. Maybe because of pytorch version? I use pytorch 0.4.0

**Comment by sklf** [comment]
> Hi, @sklf. Maybe because of pytorch version? I use pytorch 0.4.0

Yeah，I intalled the pytorch 0.4.0 and change my python from 3.6 to 2.7. Finally it worked! I think you should write some python requirements in the README ^_^. Anyway, thank you very much!
